Import Geant4 0.1.0 source tree

diff --git a/examples/extended/E02/exampleE02run b/examples/extended/E02/exampleE02run
--- a/examples/extended/E02/exampleE02run
+++ b/examples/extended/E02/exampleE02run
@@ -1,27 +1,28 @@
 #! /bin/csh -f
 
+# setup some variables (example on CERN AFS SUN-CC)
+
+set CWD          = `pwd`
+set G4ROOT       = ${CWD}/../../..
+set G4BIN        = ${G4ROOT}/bin/SUN-CC
+set G4SCHEMA_DIR = ${G4ROOT}/schema
+
+# check some configurations
+
 if ( ! $?G4EXAMPLE_FDID ) then
   echo "G4EXAMPLE_FDID is not defined.  Stop."
   exit 2
 endif
 
-# setup some variables
+if ( ! $?G4EXAMPLE_BOOT ) then
+  echo "G4EXAMPLE_BOOT is not defined.  Stop."
+  exit 2
+endif
 
-set CWD          = `pwd`
-set G4SYSTEM     = AIX-AFS
-set G4BIN        = ${CWD}/../../../bin/${G4SYSTEM}
-set G4SCHEMA_DIR = ${CWD}/../../../schema
-
-#### remove used database files
-###
-###set file = ${G4EXAMPLE_BOOT}      ; if (-e $file) rm $file
-###set file = ${G4EXAMPLE_BOOT}.FDDB ; if (-e $file) rm $file
-###cd $G4EXAMPLE_BOOT_DIR
-###rm -f Events.*.DB Geometry.*.DB System.*.DB core
-###
-###echo "Creating a federated database  $G4EXAMPLE_BOOT"
-###${HEP_ODBMS_DIR}/etc/getdb \
-###${G4SCHEMA_DIR}/G4SCHEMA $G4EXAMPLE_BOOT $G4EXAMPLE_FDID
+if ( ! -e $G4EXAMPLE_BOOT ) then
+  echo "G4EXAMPLE_BOOT is not found.  Run "gmake cleandb" first."
+  exit 2
+endif
 
 # Since the name of the federated database file G4EXAMPLE is hard
 # coded into the executable for now, it is neccessary to run it in
